name: baker-dev
channels:
- https://www.idiap.ch/software/bob/conda
- anjos
- defaults
dependencies:
- python=3.7
- six
- docopt
- b2>=1.4.2
- restic>=0.9.5
- schedule
- jinja2
- ipdb
- bob.buildout
- mr.developer
