name: baker-dev
channels:
- anjos
- conda-forge
dependencies:
- python=3.9
- docopt
- schedule
- requests
- jinja2
- b2
- restic
- pytest
# for bob.buildout
- sphinx
- sphinx_rtd_theme
- pytest-cov
- nose
- ipdb
- pip
- pip:
    - bob.buildout
