name: baker-dev
channels:
- anjos
- conda-forge
dependencies:
- python=3.8
- docopt
- schedule
- jinja2
- b2>=2.1
- restic>=0.11
- sphinx
- sphinx_rtd_theme
- nose
- coverage
- pip
- pip:
    - ipdb
    - bob.buildout
    - mr.developer
