{% set version = "0.6.0" %}

package:
  name: schedule
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/schedule/schedule-{{ version }}.tar.gz
  sha256: f9fb5181283de4db6e701d476dd01b6a3dd81c38462a54991ddbb9d26db857c9

build:
  noarch: python
  number: 0
  preserve_egg_dir: True
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  source_files:
    - test_schedule.py

  requires:
    - nose
    - mock

  imports:
    - schedule

  commands:
    - nosetests -sv test_schedule.py

about:
  home: https://github.com/dbader/schedule
  license: MIT
  summary: 'Job scheduling for humans'

extra:
  recipe-maintainers:
    - anjos
