{% set version = "0.23.0" %}

package:
  name: yapf
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/y/yapf/yapf-{{ version }}.tar.gz
  sha256: 330632d2592e67571ef2c113fe6f5802e2fa5d657448755d5546eea00693dc31

build:
  number: 0
  preserve_egg_dir: True
  entry_points:
    - yapf = yapf:run_main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  requires:
    - nose

  imports:
    - yapf

  commands:
    - nosetests yapftests

about:
  home: https://github.com/google/yapf
  license: Apache-2.0
  summary: 'A formatter for Python code'

extra:
  recipe-maintainers:
    - anjos
