{% set name = "b2sdk" %}
{% set version = "0.1.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/Backblaze/b2-sdk-python
  git_rev: v{{ version }}

build:
  noarch: python
  number: 0
  preserve_egg_dir: True
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip

  run:
    - python
    - arrow >=0.8.0
    - logfury >=0.1.2
    - requests >=2.9.1
    - six >=1.10
    - tqdm >=4.5.0

test:
  source_files:
    - test

  requires:
    - nose
    - mock
    - pyflakes
    - yapf

  imports:
    - b2sdk

  commands:
    - nosetests test/test_*.py

about:
  home: https://github.com/Backblaze/b2-sdk-python
  license: MIT
  summary: 'Python library to access B2 cloud storage'

extra:
  recipe-maintainers:
    - anjos
