{% set name = "b2sdk" %}
{% set version = "1.13.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/Backblaze/b2-sdk-python
  git_rev: v{{ version }}
  patches:
    - no_setup_requires.patch

build:
  noarch: python
  number: 0
  preserve_egg_dir: True
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools_scm >=6.2

  run:
    - python
    - setuptools >=45
    - importlib-metadata >=3.3.0  # [py<=38]
    - arrow >=0.8.0
    - logfury >=1.0.1
    - requests >=2.9.1
    - tqdm >=4.5.0

test:
  source_files:
    - test/

  requires:
    - pytest
    - pytest-mock
    - pytest-lazy-fixture
    - pyflakes
    - yapf

  imports:
    - b2sdk

  commands:
    - pytest --api=v0 '--doctest-modules' -k 'not TestSynchronizer and not TestUpdateBucket' test/unit
    - pytest --api=v1 '--doctest-modules' -k 'not TestSynchronizer and not TestUpdateBucket' test/unit
    - pytest --api=v2 '--doctest-modules' -k 'not TestSynchronizer and not TestUpdateBucket' test/unit

about:
  home: https://github.com/Backblaze/b2-sdk-python
  license: MIT
  summary: 'Python library to access B2 cloud storage'

extra:
  recipe-maintainers:
    - anjos
