{% set name = 'baker' %}
{% set version = load_setup_py_data()['version'] %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../

build:
  noarch: python
  number: 0
  script:
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python
    - pip

  run:
    - python
    - setuptools
    - restic >=0.12.1
    - b2 >=3.0.3
    - docopt
    - jinja2
    - schedule
    - requests

test:
  imports:
    - {{ name }}

  requires:
    - pytest
    - pytest-cov

  commands:
    - pytest --capture=no --verbose --cov {{ name }} --pyargs {{ name }}

about:
  home: https://github.com/anjos/baker
  license: GPLv3
  summary: Utilities for backing-up my QNAP on BackBlaze's B2
  license_family: GPL
