{% set name = "restic" %}
{% set version = "0.11.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}_{{ version }}_linux_amd64.bz2  # [linux and x86_64]
  url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}_{{ version }}_darwin_amd64.bz2  # [osx and x86_64]
  sha256: f559e774c91f1201ffddba74d5758dec8342ad2b50a3bcd735ccb0c88839045c  # [linux and x86_64]
  sha256: 4eb7ebda84217bc575fff510a5534f5750772915d6efa435a9ce49ef5eb0b075  # [osx and x86_64]
  fn: restic.bz2

requirements:
  build:
    - bzip2

build:
  number: 0

test:
  commands:
    - restic help
    - restic version

about:
  home: https://restic.net
  license: BSD 2-Clause
  license_family: BSD
  summary: 'Fast, secure, efficient backup program'

extra:
  recipe-maintainers:
    - anjos
