{% set name = "restic" %}
{% set version = "0.9.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}_{{ version }}_linux_amd64.bz2  # [linux and x86_64]
  url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}_{{ version }}_darwin_amd64.bz2  # [osx and x86_64]
  sha256: 1ad8a76a9f966da5f7a319c49a6db071a60ebaa24d69e6d86d53d6f2bcaf11ed  # [linux and x86_64]
  sha256: 6fae4e720a4f9d3d8b9b635ac161596ab4dce24168dabd75e41ccead6915a454  # [osx and x86_64]
  fn: restic.bz2

requirements:
  build:
    - bzip2

build:
  number: 0

test:
  commands:
    - restic help
    - restic version

about:
  home: https://restic.net
  license: BSD 2-Clause
  license_family: BSD
  summary: 'Fast, secure, efficient backup program'

extra:
  recipe-maintainers:
    - anjos
