{% set version = "0.1.2" %}

package:
  name: logfury
  version: {{ version }}

source:
  git_url: https://github.com/ppolewicz/logfury
  git_rev: {{ version }}

build:
  number: 0
  preserve_egg_dir: True
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - six
    - funcsigs

test:
  source_files:
    - test

  requires:
    - nose
    - pyflakes
    - yapf
    - testfixtures

  imports:
    - logfury

  commands:
    - nosetests -sv test/v0_1/*.py

about:
  home: https://github.com/ppolewicz/logfury
  license: BSD3
  summary: 'Toolkit for responsible, low-boilerplate logging of library method calls'

extra:
  recipe-maintainers:
    - anjos
