{% set version = "1.0.1" %}

package:
  name: logfury
  version: {{ version }}

source:
  git_url: https://github.com/ppolewicz/logfury
  git_rev: v{{ version }}
  patches:
    - no_setup_requires.patch

build:
  noarch: python
  number: 1
  preserve_egg_dir: True
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  source_files:
    - test

  requires:
    - pytest
    - pytest-cov
    - pyflakes
    - yapf
    - testfixtures

  imports:
    - logfury

  commands:
    - pytest -sv test/v1/*.py

about:
  home: https://github.com/ppolewicz/logfury
  license: BSD3
  summary: 'Toolkit for responsible, low-boilerplate logging of library method calls'

extra:
  recipe-maintainers:
    - anjos
