{% set name = "b2" %}
{% set version = "2.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/Backblaze/B2_Command_Line_Tool
  git_rev: v{{ version }}

build:
  noarch: python
  number: 0
  preserve_egg_dir: True
  entry_points:
    - b2 = b2.console_tool:main
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip

  run:
    - python
    - b2sdk >=1.2.0
    - arrow >=0.8.0
    - phx-class-registry =3.0.5

test:
  source_files:
    - test/

  requires:
    - pytest
    - mock
    - pyflakes
    - yapf

  imports:
    - b2

  commands:
    - pytest --doctest-modules -k 'not test_integration' test/unit test/integration

about:
  home: https://github.com/Backblaze/B2_Command_Line_Tool
  license: MIT
  summary: 'Command Line Tool for Backblaze B2'

extra:
  recipe-maintainers:
    - anjos
