package:
  name: b2
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').lstrip('v') + 'p' + environ.get('GIT_DESCRIBE_NUMBER', '') }}

source:
  git_url: https://github.com/Backblaze/B2_Command_Line_Tool
  git_rev: bbe4b73fc1a21e3476235e603a2fde8ff8a09ab3

build:
  number: 0
  preserve_egg_dir: True
  entry_points:
    - b2 = b2.console_tool:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - arrow >=0.8.0,<0.12.1
    - logfury >=0.1.2
    - requests >=2.9.1
    - six >=1.10
    - tqdm >=4.5.0
    - futures >=3.0.5  # [py27]

test:
  source_files:
    - test
    - test_b2_command_line.py

  requires:
    - nose
    - mock
    - pyflakes
    - yapf

  imports:
    - b2

  commands:
    - nosetests test/test_*.py

about:
  home: https://github.com/Backblaze/B2_Command_Line_Tool
  license: MIT
  summary: 'Command Line Tool for Backblaze B2'

extra:
  recipe-maintainers:
    - anjos
