{% set name = "b2" %}
{% set version = "3.0.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/Backblaze/B2_Command_Line_Tool
  git_rev: v{{ version }}
  patches:
    - no_setup_requires.patch

build:
  noarch: python
  number: 0
  preserve_egg_dir: True
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.5
    - pip
    - wheel
    - setuptools_scm >=6.2

  run:
    - python
    - setuptools >=45
    - importlib-metadata >=3.3.0  # [py<38]
    - b2sdk >=1.13.0
    - arrow>=0.8.0,<1.0.0
    - phx-class-registry =3.0.5
    - rst2ansi =0.1.5
    - docutils =0.16

test:
  source_files:
    - test/

  requires:
    - pytest
    - pytest-mock
    - pyflakes
    - yapf

  imports:
    - b2

  commands:
    - pytest --doctest-modules -k 'not test_integration and not test_get_account_info' test/unit test/integration

about:
  home: https://github.com/Backblaze/B2_Command_Line_Tool
  license: MIT
  summary: 'Command Line Tool for Backblaze B2'

extra:
  recipe-maintainers:
    - anjos
